# Generated by Django 5.2.1 on 2025-05-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='corrections',
            table_comment='table des corrections et des status',
        ),
    ]
