# Generated by Django 5.2.1 on 2025-05-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_corrections_table_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityCriteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Critère d'accessibilité",
                'verbose_name_plural': "Critères d'accessibilité",
                'db_table': 'accessibility_criteria',
                'ordering': ['-weight', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccessibilityLevels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level_number', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('estimated_learning_time', models.CharField(blank=True, max_length=255, null=True)),
                ('level_order', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Niveau d'accessibilité",
                'verbose_name_plural': "Niveaux d'accessibilité",
                'db_table': 'accessibility_levels',
                'ordering': ['level_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageAccessibilityEvaluations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(db_column='score')),
                ('justification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Évaluation d'accessibilité",
                'verbose_name_plural': "Évaluations d'accessibilité",
                'db_table': 'language_accessibility_evaluations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageAccessibilityLevels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('accessibility_score', models.FloatField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Niveau d'accessibilité du langage",
                'verbose_name_plural': "Niveaux d'accessibilité des langages",
                'db_table': 'language_accessibility_levels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageFeatures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('feature_type', models.CharField(max_length=50)),
                ('is_boolean', models.BooleanField(default=False)),
                ('has_multiple_values', models.BooleanField(default=False)),
                ('possible_values', models.JSONField(blank=True, null=True)),
                ('default_value', models.CharField(blank=True, max_length=100, null=True)),
                ('importance_weight', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
                ('icon_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caractéristique de langage',
                'verbose_name_plural': 'Caractéristiques de langage',
                'db_table': 'language_features',
                'ordering': ['display_order', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageFeatureValues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Valeur de caractéristique',
                'verbose_name_plural': 'Valeurs de caractéristiques',
                'db_table': 'language_feature_values',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='languagesframework',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Framework', 'verbose_name_plural': 'Frameworks'},
        ),
    ]
