# Generated by Django 5.2.1 on 2025-05-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_accessibilitycriteria_accessibilitylevels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('feature_type', models.CharField(max_length=50)),
                ('is_boolean', models.BooleanField(default=False)),
                ('has_multiple_values', models.BooleanField(default=False)),
                ('possible_values', models.JSONField(blank=True, null=True)),
                ('default_value', models.CharField(blank=True, max_length=100, null=True)),
                ('importance_weight', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
                ('icon_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caractéristique',
                'verbose_name_plural': 'Caractéristiques',
                'db_table': 'features',
                'ordering': ['display_order', 'name'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='LanguageFeature',
        ),
        migrations.AlterModelOptions(
            name='languagefeatures',
            options={'managed': False, 'verbose_name': 'Caractéristique de langage', 'verbose_name_plural': 'Caractéristiques de langage'},
        ),
    ]
