# Generated by Django 5.2.1 on 2025-05-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visiteurice'), ('registered', 'Utilisateurice enregistré.e'), ('verified', 'Utilisateurice vérifié.e'), ('validator', 'Validateurice'), ('language_referent', 'Référent.e linguistique'), ('admin', 'Administrateurice')], default='registered', max_length=20, verbose_name="Rôle de l'utilisateurice"),
        ),
    ]
