# Generated by Django 5.2.1 on 2025-05-18 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('utilisateurs', '0002_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu du commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='languages.corrections')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire de correction',
                'verbose_name_plural': 'Commentaires de corrections',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LanguageExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_level', models.CharField(choices=[('specialist', 'Spécialiste'), ('expert', 'Expert.e'), ('maintainer', 'Mainteneur.euse')], default='specialist', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Notes sur l'expertise (certifications, expérience, etc.)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experts', to='languages.languages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_expertise', to='utilisateurs.profile')),
            ],
            options={
                'verbose_name': 'Expertise en langage',
                'verbose_name_plural': 'Expertises en langages',
                'unique_together': {('user', 'language')},
            },
        ),
    ]
