# Generated by Django 5.2.1 on 2025-05-22 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_modify_profile_primary_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='languageexpertise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='languageexpertise',
            name='expertise_level',
            field=models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('specialist', 'Spécialiste'), ('expert', 'Expert')], default='intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='languageexpertise',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='languageexpertise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_expertise', to=settings.AUTH_USER_MODEL),
        ),
    ]
