# Generated by Django 5.2.1 on 2025-05-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Documentation BDD',
                'verbose_name_plural': 'Documentation BDD',
                'managed': False,
            },
        ),
    ]
